spring.application.name=ProyectoCorte2


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

server.port=${PORT:8080}


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.thymeleaf=DEBUG

spring.main.allow-circular-references=true
