# Nombre de la aplicación
spring.application.name=ProyectoCorte2


# ===============================
# DATABASE POSTGRESQL (RENDER)
# ===============================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# HIBERNATE / JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.open-in-view=false


# ===============================
# LOGS
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.thymeleaf=DEBUG


# ===============================
# SERVER
# ===============================

server.port=${PORT:8080}


# Permitir referencias circulares
spring.main.allow-circular-references=true
